name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker exec my.nestjs.app dockerize -timeout=200s -wait=http://localhost:3000/
      - run: docker exec my.nestjs.app npm run test